[package]
authors = ["Johnny Human <johnnyhuman@protonmail.ch>"]
name = "nlp"
version = "0.1.0"

[dependencies]
bitflags = "0.9.0"
clap = "2.24.1"
encoding = "0.2.33"
filebuffer = "0.1.1"
fst = "0.1.38"
serde = "1.0.8"
time = "0.1.37"
